#!/bin/bash
sudo dnf -y update
sudo dnf install -y postgresql12-server postgresql12-contrib
sudo systemctl start postgresql12
sudo -u postgres psql <<EOF

CREATE USER demoekz  WITH PASSWORD '12345678';

CREATE DATABASE demoekzbd OWNER demoekz;

GRANT ALL PRIVILEGES ON DATABASE demoekzbd TO demoekz;

\c demoekzbd

SET ROLE demoekz;



CREATE TABLE roles (
    role_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    user_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    login VARCHAR(50) NOT NULL UNIQUE,
    role_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE categories (
    category_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE subcategories (
    subcategory_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id INT NOT NULL,
    subcategory_name VARCHAR(100) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT uq_category_subcategory UNIQUE (category_id, subcategory_name)
);

CREATE TABLE manufacturers (
    manufacturer_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    manufacturer_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE products (
    product_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    subcategory_id INT NOT NULL,
    manufacturer_id INT NOT NULL,
    image_url VARCHAR(255),
    description TEXT,
    composition TEXT,
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(subcategory_id),
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(manufacturer_id)
);

CREATE TABLE sizes (
    size_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    size_value DECIMAL(4, 1) NOT NULL UNIQUE
);

CREATE TABLE stock_items (
    stock_item_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    size_id INT NOT NULL,
    quantity_available INT NOT NULL DEFAULT 0 CHECK (quantity_available >= 0),
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (size_id) REFERENCES sizes(size_id),
    CONSTRAINT uq_product_size UNIQUE (product_id, size_id)
);

CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE order_items (
    order_item_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    stock_item_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price_per_unit DECIMAL(10, 2) NOT NULL CHECK (price_per_unit >= 0),
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (stock_item_id) REFERENCES stock_items(stock_item_id),
    CONSTRAINT uq_order_stock_item UNIQUE (order_id, stock_item_id)
);

INSERT INTO roles (role_id, role_name) OVERRIDING SYSTEM VALUE VALUES
(1, 'Авторизованный пользователь'),
(2, 'Администратор'),
(3, 'Менеджер');

INSERT INTO users (user_id, last_name, first_name, patronymic, login, role_id) OVERRIDING SYSTEM VALUE VALUES
(1, 'Иванов', 'Иван', 'Сергеевич', 'isivanov', 2),
(2, 'Петров', 'Пeтр', 'Алексеевич', 'papetrov', 3),
(3, 'Сидорова', 'Анна', 'Дмитриевна', 'asidorova', 1),
(4, 'Кузнецова', 'Екатерина', 'Андреевна', 'ekuznetsova', 3),
(5, 'Смирнов', 'Дмитрий', 'Владимирович', 'dsmirnov', 1),
(6, 'Попов', 'Алексей', 'Николаевич', 'apopov', 2),
(7, 'Васильева', 'Ольга', 'Игоревна', 'ovasileva', 1),
(8, 'Соколов', 'Павел', 'Викторович', 'psokolov', 3),
(9, 'Михайлова', 'Татьяна', 'Юрьевна', 'tmikhailova', 1),
(10, 'Новикова', 'Наталья', 'Сергеевна', 'nnovikova', 3),
(11, 'Фёдоров', 'Андрей', 'Максимович', 'afedorov', 2),
(12, 'Морозов', 'Сергей', 'Павлович', 'smorozov', 1),
(13, 'Волкова', 'Юлия', 'Александровна', 'jvolkova', 3),
(14, 'Алексеев', 'Артём', 'Евгеньевич', 'aalekseev', 1),
(15, 'Лебедева', 'Ирина', 'Владимировна', 'ilebedeva', 1),
(16, 'Егоров', 'Никита', 'Денисович', 'negorov', 3),
(17, 'Павлова', 'Елена', 'Петровна', 'epavlova', 1),
(18, 'Козлов', 'Роман', 'Олегович', 'rkozlov', 2),
(19, 'Степанова', 'Виктория', 'Романовна', 'vstepanova', 3),
(20, 'Николаев', 'Владимир', 'Иванович', 'vnikolaev', 1);

INSERT INTO categories (category_id, category_name) OVERRIDING SYSTEM VALUE VALUES
(1, 'Детская обувь'),
(2, 'Женская обувь'),
(3, 'Мужская обувь');

INSERT INTO subcategories (subcategory_id, category_id, subcategory_name) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 'Кроссовки'),
(2, 1, 'Сапоги'),
(3, 1, 'Босоножки'),
(4, 1, 'Туфли'),
(5, 2, 'Сапоги'),
(6, 2, 'Босоножки'),
(7, 2, 'Туфли'),
(8, 2, 'Кроссовки'),
(9, 3, 'Кроссовки'),
(10, 3, 'Туфли'),
(11, 3, 'Ботинки');

INSERT INTO manufacturers (manufacturer_id, manufacturer_name) OVERRIDING SYSTEM VALUE VALUES
(1, 'Азимут'),
(2, 'Барбари'),
(3, 'Берестов'),
(4, 'Весна'),
(5, 'Здоровый шаг'),
(6, 'Карапуз'),
(7, 'Кожевенные традиции'),
(8, 'Лапушка'),
(9, 'Маленький франт'),
(10, 'Малыш-Спорт'),
(11, 'Модный силуэт'),
(12, 'Северята'),
(13, 'Стиль и комфорт'),
(14, 'Твой комфорт'),
(15, 'Топ-Топ'),
(16, 'Тёплые ножки');

INSERT INTO products (product_id, product_name, subcategory_id, manufacturer_id, image_url, description, composition, price) OVERRIDING SYSTEM VALUE VALUES
(1, 'Кроссовки детские «Звёздочка» экокожа', 1, 10, 'IMG_KS_195217.png', 'Кроссовки детские «Звёздочка» экокожа. Производитель: ООО «Малыш-Спорт», г. Смоленск', 'Верх — экокожа (полиуретан на хлопковой основе), подкладка — хлопок 100%, подошва — ПВХ', 2190.00),
(2, 'Кроссовки детские «Гонщик» экокожа', 1, 15, 'IMG_KS_195213.png', 'Кроссовки детские «Гонщик» экокожа. Производитель: Фабрика «Топ-Топ», г. Киров', 'Верх — экокожа (микрофибра), подкладка — текстиль сетчатый (полиэстер), подошва — термопластичная резина (ТЭП)', 2490.00),
(3, 'Кроссовки детские «Радуга» экокожа перфорированная', 1, 8, 'IMG_KS_195209.png', 'Кроссовки детские «Радуга» экокожа перфорированная. Производитель: ООО «Лапушка», г. Воронеж', 'Верх — экокожа перфорированная (полиуретан), подкладка — хлопок 100%, стелька — натуральная кожа, подошва — ЭВА', 2290.00),
(4, 'Сапожки детские «Снежинка» зимние на меху', 2, 16, 'IMG_KS_195205.png', 'Сапожки детские «Снежинка» зимние на меху. Производитель: Фабрика «Тёплые ножки», г. Вологда', 'Верх — текстиль с водоотталкивающей пропиткой (нейлон 100%), подкладка и стелька — шерстяной мех (80% шерсть, 20% полиэстер), подошва — ТЭП', 3190.00),
(5, 'Сапожки детские «Медвежонок» демисезонные непромокаемые', 2, 12, 'IMG_KS_195201.png', 'Сапожки детские «Медвежонок» демисезонные непромокаемые. Производитель: ООО «Северята», г. Мурманск', 'Верх — мембранная ткань (полиэстер 100%), подкладка — флис (полиэстер 100%), подошва — ЭВА с противоскользящим протектором', 2890.00),
(6, 'Сапожки детские «Принцесса» кожаные', 2, 4, 'IMG_KS_195197.png', 'Сапожки детские «Принцесса» кожаные. Производитель: ООО «Весна», г. Тверь', 'Верх — натуральная кожа (телячья), подкладка — байка (хлопок 100%), подошва — терморезина', 3590.00),
(7, 'Сандалии детские «Пчёлка» ортопедические летние', 3, 5, 'IMG_KS_195193.png', 'Сандалии детские «Пчёлка» ортопедические летние. Производитель: Ортопедическая фабрика «Здоровый шаг», г. Владимир', 'Верх — натуральная кожа (кожа КРС), подкладка — натуральная кожа, стелька — с анатомическим супинатором, подошва — микропористая резина', 2790.00),
(8, 'Сандалии детские «Морячок» текстильные с фиксатором', 3, 6, 'IMG_KS_195189.png', 'Сандалии детские «Морячок» текстильные с фиксатором. Производитель: ООО «Карапуз», г. Иваново', 'Верх — текстиль (хлопок 100%), подкладка — текстиль, подошва — ПВХ лёгкий', 1690.00),
(9, 'Туфли детские «Бантик» лаковые праздничные', 4, 9, 'IMG_KS_195185.png', 'Туфли детские «Бантик» лаковые праздничные. Производитель: Фабрика «Маленький франт», г. Нижний Новгород', 'Верх — экокожа лаковая (полиуретан), подкладка — натуральная кожа (коза), подошва — тунит (кожволон)', 2390.00),
(10, 'Сапоги зимние натуральная кожа', 5, 2, 'IMG_KS_195218.jpg', 'Сапоги зимние из натуральной кожи с подкладкой из натурального меха', 'Натуральная кожа, натуральный мех', 25000.00),
(11, 'Сапоги осенние натуральная кожа', 5, 2, 'IMG_KS_195214.png', 'Элегантные женские демисезонные сапоги из мягкой гладкой кожи.', 'Натуральная кожа, байка', 15000.00),
(12, 'Сапоги трубы демисезонные замшевые', 5, 14, 'IMG_KS_195210.png', 'Сапоги-трубы без застежки из натуральной замши глубокого шоколадного оттенка.', 'Натуральная замша, текстиль', 17000.00),
(13, 'Босоножки «Песчаный берег» коричневые', 6, 13, 'IMG_KS_195206.png', 'Легкие босоножки из мягкой натуральной кожи на устойчивом среднем каблуке.', '100% натуральная кожа', 7500.00),
(14, 'Женские босоножки «Черный кофе» со скульптурным каблуком', 6, 7, 'IMG_KS_195202.png', 'Изящные босоножки с ремешком вокруг щиколотки и оригинальным каблуком.', 'Натуральная кожа, тунит', 8565.00),
(15, 'Босоножки женские «Летний бриз»', 6, 11, 'IMG_KS_195198.png', 'Лаконичные босоножки на плоском ходу с мелкими переплетенными ремешками.', 'Натуральная кожа, резины', 7757.00),
(16, 'Демисезонные туфли натуральная кожа', 7, 11, 'IMG_KS_195194.png', 'Классические туфли-дерби на утолщенной подошве из натуральной кожи.', 'Натуральная кожа, ТЭП', 7130.00),
(17, 'Туфли женские натуральная кожа с металлическими вставками', 7, 7, 'IMG_KS_195190.png', 'Современные туфли с острым носом и акцентным металлическим деком на каблуке.', 'Натуральная кожа, металл', 12340.00),
(18, 'Туфли классические лодочки натуральная кожа', 7, 13, 'IMG_KS_195186.png', 'Элегантные туфли-лодочки на шпильке 8 см из премиальной гладкой кожи.', '100% натуральная кожа', 7550.00),
(19, 'Кроссовки белые с оранжевым и красным', 8, 15, 'IMG_KS_195182.png', 'Яркие женские кроссовки в стиле ретро из комбинированных материалов.', 'Экокожа, замша, текстиль', 8765.00),
(20, 'Кроссовки летние кожаные', 8, 15, 'IMG_KS_195178.png', 'Легкие дышащие кроссовки с перфорацией для горячего летнего сезона.', 'Натуральная кожа, ЭВА', 7795.00),
(21, 'Кроссовки кожаные', 9, 13, 'IMG_KS_195219.png', 'Классические мужские кроссовки из плотной кожи для ежедневной носки.', 'Натуральная кожа, резина', 9567.00),
(22, 'Кроссовки «Стиль и комфорт»', 9, 13, 'IMG_KS_195215.png', 'Анатомические кроссовки с усиленной поддержкой стопы.', 'Натуральная кожа, текстиль', 7890.00),
(23, 'Кроссовки для бега «Драйв»', 9, 1, 'IMG_KS_195211.png', 'Профессиональные беговые кроссовки с амортизирующей подошвой.', 'Текстиль, сетка, ЭВА', 6550.00),
(24, 'Кроссовки «Азимут Бег»', 9, 1, 'IMG_KS_195207.png', 'Легкие кроссовки для пробежек и тренировок в зале.', 'Сетчатый текстиль, филон', 4290.00),
(25, 'Кроссовки', 9, 15, 'IMG_KS_195203.png', 'Универсальные базовые кроссовки из практичных материалов.', 'Экокожа, текстиль', 5000.00),
(26, 'Черные туфли в классическом стиле — база для деловых образов', 10, 2, 'IMG_KS_195199.png', 'Мужские классические туфли-оксфорды из высококачественной кожи.', 'Натуральная кожа', 24569.00),
(27, 'Туфли мужские светлые классика демисезонные', 10, 3, 'IMG_KS_195195.png', 'Классические туфли бежево-песочного оттенка с перфорацией.', 'Натуральная кожа', 14567.00),
(28, 'Туфли из натуральной кожи', 10, 3, 'IMG_KS_195191.png', 'Строгие мужские туфли без лишних деталей на тонкой подошве.', 'Натуральная кожа', 15670.00),
(29, 'Ботинки мужские демисезонные', 11, 2, 'IMG_KS_195187.png', 'Удобные ботинки на шнуровке с байковой подкладкой для прохладной погоды.', 'Натуральная кожа, байка', 21500.00),
(30, 'Ботинки черные из натуральной кожи', 11, 7, 'IMG_KS_195183.png', 'Прочные мужские ботинки в стиле милитари на толстой подошве.', 'Натуральная кожа, ТЭП', 25625.00),
(31, 'Ботинки зимние классические', 11, 2, 'IMG_KS_195179.png', 'Теплые классические ботинки на натуральном меху.', 'Натуральная кожа, натуральный мех', 22000.00);

INSERT INTO sizes (size_id, size_value) OVERRIDING SYSTEM VALUE VALUES
(1, 18.0),
(2, 19.0),
(3, 20.0),
(4, 21.0),
(5, 22.0),
(6, 23.0),
(7, 24.0),
(8, 25.0),
(9, 26.0),
(10, 27.0),
(11, 28.0),
(12, 29.0),
(13, 30.0),
(14, 31.0),
(15, 32.0),
(16, 33.0),
(17, 34.0),
(18, 35.0),
(19, 36.0),
(20, 36.5),
(21, 37.0),
(22, 37.5),
(23, 38.0),
(24, 38.5),
(25, 39.0),
(26, 39.5),
(27, 40.0),
(28, 40.5),
(29, 41.0),
(30, 41.5),
(31, 42.0),
(32, 42.5),
(33, 43.0),
(34, 44.0),
(35, 45.0);

INSERT INTO stock_items (stock_item_id, product_id, size_id, quantity_available) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 3, 20),
(2, 1, 4, 20),
(3, 1, 5, 20),
(4, 1, 6, 20),
(5, 1, 7, 20),
(6, 1, 8, 20),
(7, 2, 3, 20),
(8, 2, 4, 20),
(9, 2, 5, 20),
(10, 2, 6, 20),
(11, 2, 7, 20),
(12, 2, 8, 20),
(13, 3, 3, 15),
(14, 3, 4, 15),
(15, 3, 5, 15),
(16, 4, 3, 10),
(17, 4, 4, 10),
(18, 4, 5, 10),
(19, 5, 3, 10),
(20, 7, 5, 10),
(21, 7, 6, 10),
(22, 7, 7, 10),
(23, 8, 3, 15),
(24, 8, 4, 15),
(25, 8, 5, 15),
(26, 9, 5, 10),
(27, 9, 6, 10),
(28, 9, 7, 10),
(29, 10, 23, 5),
(30, 10, 25, 5),
(31, 10, 27, 5),
(32, 11, 21, 10),
(33, 11, 23, 10),
(34, 12, 21, 7),
(35, 12, 23, 7),
(36, 12, 25, 7),
(37, 13, 19, 10),
(38, 13, 21, 10),
(39, 13, 23, 10),
(40, 13, 25, 10),
(41, 13, 27, 10),
(42, 14, 18, 3),
(43, 15, 21, 23),
(44, 15, 25, 23),
(45, 15, 27, 23),
(46, 16, 19, 25),
(47, 16, 21, 25),
(48, 16, 23, 25),
(49, 17, 19, 4),
(50, 17, 23, 4),
(51, 17, 25, 4),
(52, 17, 27, 4),
(53, 18, 18, 9),
(54, 18, 23, 9),
(55, 19, 18, 2),
(56, 19, 19, 2),
(57, 20, 21, 5),
(58, 20, 22, 5),
(59, 20, 23, 5),
(60, 20, 24, 5),
(61, 21, 18, 16),
(62, 21, 19, 16),
(63, 21, 23, 16),
(64, 21, 25, 16),
(65, 22, 18, 3),
(66, 22, 23, 3),
(67, 23, 30, 18),
(68, 23, 31, 18),
(69, 23, 32, 18),
(70, 23, 33, 18),
(71, 24, 23, 50),
(72, 24, 24, 50),
(73, 24, 25, 50),
(74, 24, 26, 50),
(75, 24, 27, 50),
(76, 24, 29, 50),
(77, 25, 29, 3),
(78, 25, 31, 3),
(79, 25, 34, 3),
(80, 26, 27, 23),
(81, 26, 29, 23),
(82, 26, 33, 23),
(83, 27, 31, 15),
(84, 27, 33, 15),
(85, 27, 34, 15),
(86, 28, 34, 3),
(87, 29, 29, 1),
(88, 29, 31, 1),
(89, 30, 31, 20),
(90, 30, 33, 20),
(91, 31, 29, 30),
(92, 31, 31, 30);

-- 9. Заказы (Заголовки)
INSERT INTO orders (order_id, order_date, user_id) VALUES
(1, '2026-04-02', 3),
(2, '2026-04-05', 17),
(3, '2026-04-08', 7),
(4, '2026-04-12', 15),
(5, '2026-04-18', 12),
(6, '2026-04-22', 9),
(7, '2026-04-25', 14),
(8, '2026-04-28', 20),
(9, '2026-05-05', 5),
(10, '2026-05-08', 17);

INSERT INTO order_items (order_item_id, order_id, stock_item_id, quantity, price_per_unit) OVERRIDING SYSTEM VALUE VALUES
(1, 1, 1, 1, 2190.00),
(2, 1, 20, 1, 2790.00),
(3, 2, 30, 1, 25000.00),
(4, 2, 39, 1, 7500.00),
(5, 3, 34, 1, 17000.00),
(6, 3, 57, 1, 8565.00),
(7, 3, 65, 1, 7795.00),
(8, 4, 50, 1, 7757.00),
(9, 4, 48, 1, 12340.00),
(10, 4, 44, 1, 7130.00),
(11, 4, 62, 1, 8765.00),
(12, 4, 32, 1, 15000.00),
(13, 5, 77, 1, 9567.00),
(14, 5, 87, 1, 21500.00),
(15, 5, 73, 1, 7890.00),
(16, 6, 80, 1, 24569.00),
(17, 6, 89, 1, 14567.00),
(18, 6, 91, 1, 15670.00),
(19, 7, 16, 1, 4290.00),
(20, 7, 2, 2, 2190.00),
(21, 7, 24, 1, 1690.00),
(22, 8, 86, 1, 25625.00),
(23, 8, 75, 3, 7890.00),
(24, 8, 70, 2, 6550.00),
(25, 9, 7, 1, 2490.00),
(26, 9, 14, 2, 3190.00),
(27, 10, 53, 1, 7550.00),
(28, 10, 43, 1, 7130.00),
(29, 10, 46, 1, 12340.00),
(30, 10, 61, 2, 8765.00);

SELECT setval(pg_get_serial_sequence('roles', 'role_id'), COALESCE(MAX(role_id), 1)) FROM roles;
SELECT setval(pg_get_serial_sequence('users', 'user_id'), COALESCE(MAX(user_id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('categories', 'category_id'), COALESCE(MAX(category_id), 1)) FROM categories;
SELECT setval(pg_get_serial_sequence('subcategories', 'subcategory_id'), COALESCE(MAX(subcategory_id), 1)) FROM subcategories;
SELECT setval(pg_get_serial_sequence('manufacturers', 'manufacturer_id'), COALESCE(MAX(manufacturer_id), 1)) FROM manufacturers;
SELECT setval(pg_get_serial_sequence('products', 'product_id'), COALESCE(MAX(product_id), 1)) FROM products;
SELECT setval(pg_get_serial_sequence('sizes', 'size_id'), COALESCE(MAX(size_id), 1)) FROM sizes;
SELECT setval(pg_get_serial_sequence('stock_items', 'stock_item_id'), COALESCE(MAX(stock_item_id), 1)) FROM stock_items;
SELECT setval(pg_get_serial_sequence('orders', 'order_id'), COALESCE(MAX(order_id), 1)) FROM orders;
SELECT setval(pg_get_serial_sequence('order_items', 'order_item_id'), COALESCE(MAX(order_item_id), 1)) FROM order_items;

EOF


sudo dnf install -y dbeaver
sudo dnf install -y libreoffice
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf install -y code

#!/bin/bash
mkdir $HOME/demoekz
cd $HOME/demoekz || echo "Нету директории"
python3 -m venv .venv
dolphin "$HOME"/demoekz &
source .venv/bin/activate
pip install --upgrade pip
pip install pyside6
deactivate
touch main.py
cat > main.py <<EOF
from PySide6.QtWidgets import QApplication, QMainWindow
from Register import Ui_MainWindow as RegisterUI
from Login import Ui_MainWindow as LoginUI

class RegisterWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = RegisterUI()
        self.ui.setupUi(self)

        self.ui.Login_Button.clicked.connect(self.get_text)

    def get_text(self):
        login = self.ui.Login_Box.text()
        password = self.ui.Password_Box.text()
        if login == "admin" and password == "admin":
            print(f"login:{login} password:{password}")

            self.login_window = LoginWindow()
            self.login_window.show()

            self.close()

class LoginWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = LoginUI()
        self.ui.setupUi(self)


def main():
    app = QApplication()
    window = RegisterWindow()
    window.show()
    app.exec()

if __name__ == "__main__":
    main()
EOF

touch Login.ui
cat > Login.ui <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>500</width>
    <height>640</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <widget class="QComboBox" name="comboBox">
    <property name="geometry">
     <rect>
      <x>170</x>
      <y>200</y>
      <width>82</width>
      <height>26</height>
     </rect>
    </property>
   </widget>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>500</width>
     <height>33</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>

EOF

touch Login.py
cat > Login.py <<EOF
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Login.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QMainWindow, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(500, 640)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 200, 82, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 500, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
    # retranslateUi
EOF

touch Register.ui
cat > Register.ui <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="enabled">
   <bool>true</bool>
  </property>
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>500</width>
    <height>300</height>
   </rect>
  </property>
  <property name="sizePolicy">
   <sizepolicy hsizetype="Fixed" vsizetype="Fixed">
    <horstretch>0</horstretch>
    <verstretch>0</verstretch>
   </sizepolicy>
  </property>
  <property name="maximumSize">
   <size>
    <width>500</width>
    <height>300</height>
   </size>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <property name="layoutDirection">
   <enum>Qt::LayoutDirection::LeftToRight</enum>
  </property>
  <widget class="QWidget" name="centralwidget">
   <property name="enabled">
    <bool>true</bool>
   </property>
   <layout class="QGridLayout" name="gridLayout">
    <item row="0" column="1">
     <spacer name="verticalSpacer">
      <property name="orientation">
       <enum>Qt::Orientation::Vertical</enum>
      </property>
      <property name="sizeHint" stdset="0">
       <size>
        <width>20</width>
        <height>90</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row="1" column="0">
     <spacer name="horizontalSpacer">
      <property name="orientation">
       <enum>Qt::Orientation::Horizontal</enum>
      </property>
      <property name="sizeHint" stdset="0">
       <size>
        <width>154</width>
        <height>20</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row="1" column="2">
     <spacer name="horizontalSpacer_2">
      <property name="orientation">
       <enum>Qt::Orientation::Horizontal</enum>
      </property>
      <property name="sizeHint" stdset="0">
       <size>
        <width>154</width>
        <height>20</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row="3" column="1">
     <spacer name="verticalSpacer_2">
      <property name="orientation">
       <enum>Qt::Orientation::Vertical</enum>
      </property>
      <property name="sizeHint" stdset="0">
       <size>
        <width>20</width>
        <height>90</height>
       </size>
      </property>
     </spacer>
    </item>
    <item row="1" column="1">
     <layout class="QVBoxLayout" name="verticalLayout">
      <item>
       <widget class="QLineEdit" name="Login_Box">
        <property name="maximumSize">
         <size>
          <width>16777215</width>
          <height>25</height>
         </size>
        </property>
       </widget>
      </item>
      <item>
       <widget class="QLineEdit" name="Password_Box">
        <property name="maximumSize">
         <size>
          <width>16777215</width>
          <height>25</height>
         </size>
        </property>
        <property name="inputMask">
         <string/>
        </property>
       </widget>
      </item>
      <item>
       <widget class="QPushButton" name="Login_Button">
        <property name="maximumSize">
         <size>
          <width>100</width>
          <height>20</height>
         </size>
        </property>
        <property name="layoutDirection">
         <enum>Qt::LayoutDirection::LeftToRight</enum>
        </property>
        <property name="text">
         <string>Login</string>
        </property>
       </widget>
      </item>
     </layout>
    </item>
   </layout>
  </widget>
 </widget>
 <resources/>
 <connections/>
</ui>

EOF

touch Register.py
cat > Register.py <<EOF

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Register.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpacerItem, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(500, 300))
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.verticalSpacer = QSpacerItem(20, 90, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer, 0, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(154, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 1, 0, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(154, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_2, 1, 2, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 90, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer_2, 3, 1, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Login_Box = QLineEdit(self.centralwidget)
        self.Login_Box.setObjectName(u"Login_Box")
        self.Login_Box.setMaximumSize(QSize(16777215, 25))

        self.verticalLayout.addWidget(self.Login_Box)

        self.Password_Box = QLineEdit(self.centralwidget)
        self.Password_Box.setObjectName(u"Password_Box")
        self.Password_Box.setMaximumSize(QSize(16777215, 25))

        self.verticalLayout.addWidget(self.Password_Box)

        self.Login_Button = QPushButton(self.centralwidget)
        self.Login_Button.setObjectName(u"Login_Button")
        self.Login_Button.setMaximumSize(QSize(100, 20))
        self.Login_Button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.verticalLayout.addWidget(self.Login_Button)


        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Password_Box.setInputMask("")
        self.Login_Button.setText(QCoreApplication.translate("MainWindow", u"Login", None))
    # retranslateUi


EOF

#code .

source .venv/bin/activate
python3 main.py

